%include "!userprofile\desktop\sas\decalogue2\__signon.sas";
%include "!userprofile\desktop\sas\decalogue2\_n.sas";
%include "!userprofile\desktop\sas\decalogue2\_r.sas";
%include "!userprofile\desktop\sas\decalogue2\_rank.sas";
%include "!userprofile\desktop\sas\decalogue2\_s.sas";
%include "!userprofile\desktop\sas\decalogue2\_t.sas";
%include "!userprofile\desktop\sas\decalogue2\_u.sas";
%include "!userprofile\desktop\sas\decalogue2\_zoom.sas";

%include "!userprofile\desktop\sas\decalogue2\exchcd.sas";
%include "!userprofile\desktop\sas\decalogue2\ret.sas";
%include "!userprofile\desktop\sas\decalogue2\reu.sas";

%include "!userprofile\desktop\sas\decalogue2\bm\_bm.sas";
%include "!userprofile\desktop\sas\decalogue2\bm\_bn.sas";
%include "!userprofile\desktop\sas\decalogue2\bm\pctl_bm.sas";
%include "!userprofile\desktop\sas\decalogue2\bm\rank_bm.sas";
%include "!userprofile\desktop\sas\decalogue2\bm\ret_bm.sas";
%include "!userprofile\desktop\sas\decalogue2\bm\ret_bm_.sas";
rsubmit; %ret_bm_(5,z1.); endrsubmit;
rsubmit; %ret_bm_(10,z1.); endrsubmit;
%include "!userprofile\desktop\sas\decalogue2\bm\ret_bm_010_d009.sas";
rsubmit; %ret_bm_(25,z2.); endrsubmit;
rsubmit; %ret_bm_(50,z2.); endrsubmit;
rsubmit; %ret_bm_(100,z2.); endrsubmit;
rsubmit; %ret_bm_(200,z3.); endrsubmit;
%include "!userprofile\desktop\sas\decalogue2\bm\reu_bm.sas";
%include "!userprofile\desktop\sas\decalogue2\bm\reu_bm_.sas";
/*%include "!userprofile\desktop\sas\decalogue2\bm\reu_bm__.sas";*/
rsubmit; %reu_bm_(5,z1.); endrsubmit;
rsubmit; %reu_bm_(10,z1.); endrsubmit;
%include "!userprofile\desktop\sas\decalogue2\bm\reu_bm_010_d011.sas";
rsubmit; %reu_bm_(25,z2.); endrsubmit;
rsubmit; %reu_bm_(50,z2.); endrsubmit;
rsubmit; %reu_bm_(100,z2.); endrsubmit;
rsubmit; %reu_bm_(200,z3.); endrsubmit;

%include "!userprofile\desktop\sas\decalogue2\ret11\_ret11.sas";
%include "!userprofile\desktop\sas\decalogue2\ret11\pctl_ret11.sas";
%include "!userprofile\desktop\sas\decalogue2\ret11\rank_ret11.sas";
%include "!userprofile\desktop\sas\decalogue2\ret11\ret_ret11.sas";
%include "!userprofile\desktop\sas\decalogue2\ret11\ret_ret11_.sas";
rsubmit; %ret_ret11_(5,z1.); endrsubmit;
rsubmit; %ret_ret11_(10,z1.); endrsubmit;
%include "!userprofile\desktop\sas\decalogue2\ret11\ret_ret11_010_d079.sas";
rsubmit; %ret_ret11_(25,z2.); endrsubmit;
rsubmit; %ret_ret11_(50,z2.); endrsubmit;
rsubmit; %ret_ret11_(100,z2.); endrsubmit;
rsubmit; %ret_ret11_(200,z3.); endrsubmit;
%include "!userprofile\desktop\sas\decalogue2\ret11\reu_ret11.sas";
%include "!userprofile\desktop\sas\decalogue2\ret11\reu_ret11_.sas";
/*%include "!userprofile\desktop\sas\decalogue2\ret11\reu_ret11__.sas";*/
rsubmit; %reu_ret11_(5,z1.); endrsubmit;
rsubmit; %reu_ret11_(10,z1.); endrsubmit;
%include "!userprofile\desktop\sas\decalogue2\ret11\reu_ret11_010_d080.sas";
rsubmit; %reu_ret11_(25,z2.); endrsubmit;
rsubmit; %reu_ret11_(50,z2.); endrsubmit;
rsubmit; %reu_ret11_(100,z2.); endrsubmit;
rsubmit; %reu_ret11_(200,z3.); endrsubmit;
%include "!userprofile\desktop\sas\decalogue2\ret11\zoom_pctl_ret11.sas";
%include "!userprofile\desktop\sas\decalogue2\ret11\zoom_rank_ret11.sas";
%include "!userprofile\desktop\sas\decalogue2\ret11\zoom_ret_ret11.sas";
%include "!userprofile\desktop\sas\decalogue2\ret11\zoom_ret_ret11_200.sas";
%include "!userprofile\desktop\sas\decalogue2\ret11\zoom_reu_ret11.sas";
%include "!userprofile\desktop\sas\decalogue2\ret11\zoom_reu_ret11_200.sas";
