libname r "!userprofile\desktop\sas\decalogue\ret_op_in\";

rsubmit;

proc sql;
	create table ret_op_in_10x10 as
		select date,
			sum(ifn(op=0 and in=0,size1,.)*ret)/sum(ifn(op=0 and in=0,size1,.)) as o0i0,
			sum(ifn(op=0 and in=1,size1,.)*ret)/sum(ifn(op=0 and in=1,size1,.)) as o0i1,
			sum(ifn(op=0 and in=2,size1,.)*ret)/sum(ifn(op=0 and in=2,size1,.)) as o0i2,
			sum(ifn(op=0 and in=3,size1,.)*ret)/sum(ifn(op=0 and in=3,size1,.)) as o0i3,
			sum(ifn(op=0 and in=4,size1,.)*ret)/sum(ifn(op=0 and in=4,size1,.)) as o0i4,
			sum(ifn(op=0 and in=5,size1,.)*ret)/sum(ifn(op=0 and in=5,size1,.)) as o0i5,
			sum(ifn(op=0 and in=6,size1,.)*ret)/sum(ifn(op=0 and in=6,size1,.)) as o0i6,
			sum(ifn(op=0 and in=7,size1,.)*ret)/sum(ifn(op=0 and in=7,size1,.)) as o0i7,
			sum(ifn(op=0 and in=8,size1,.)*ret)/sum(ifn(op=0 and in=8,size1,.)) as o0i8,
			sum(ifn(op=0 and in=9,size1,.)*ret)/sum(ifn(op=0 and in=9,size1,.)) as o0i9,
			sum(ifn(op=1 and in=0,size1,.)*ret)/sum(ifn(op=1 and in=0,size1,.)) as o1i0,
			sum(ifn(op=1 and in=1,size1,.)*ret)/sum(ifn(op=1 and in=1,size1,.)) as o1i1,
			sum(ifn(op=1 and in=2,size1,.)*ret)/sum(ifn(op=1 and in=2,size1,.)) as o1i2,
			sum(ifn(op=1 and in=3,size1,.)*ret)/sum(ifn(op=1 and in=3,size1,.)) as o1i3,
			sum(ifn(op=1 and in=4,size1,.)*ret)/sum(ifn(op=1 and in=4,size1,.)) as o1i4,
			sum(ifn(op=1 and in=5,size1,.)*ret)/sum(ifn(op=1 and in=5,size1,.)) as o1i5,
			sum(ifn(op=1 and in=6,size1,.)*ret)/sum(ifn(op=1 and in=6,size1,.)) as o1i6,
			sum(ifn(op=1 and in=7,size1,.)*ret)/sum(ifn(op=1 and in=7,size1,.)) as o1i7,
			sum(ifn(op=1 and in=8,size1,.)*ret)/sum(ifn(op=1 and in=8,size1,.)) as o1i8,
			sum(ifn(op=1 and in=9,size1,.)*ret)/sum(ifn(op=1 and in=9,size1,.)) as o1i9,
			sum(ifn(op=2 and in=0,size1,.)*ret)/sum(ifn(op=2 and in=0,size1,.)) as o2i0,
			sum(ifn(op=2 and in=1,size1,.)*ret)/sum(ifn(op=2 and in=1,size1,.)) as o2i1,
			sum(ifn(op=2 and in=2,size1,.)*ret)/sum(ifn(op=2 and in=2,size1,.)) as o2i2,
			sum(ifn(op=2 and in=3,size1,.)*ret)/sum(ifn(op=2 and in=3,size1,.)) as o2i3,
			sum(ifn(op=2 and in=4,size1,.)*ret)/sum(ifn(op=2 and in=4,size1,.)) as o2i4,
			sum(ifn(op=2 and in=5,size1,.)*ret)/sum(ifn(op=2 and in=5,size1,.)) as o2i5,
			sum(ifn(op=2 and in=6,size1,.)*ret)/sum(ifn(op=2 and in=6,size1,.)) as o2i6,
			sum(ifn(op=2 and in=7,size1,.)*ret)/sum(ifn(op=2 and in=7,size1,.)) as o2i7,
			sum(ifn(op=2 and in=8,size1,.)*ret)/sum(ifn(op=2 and in=8,size1,.)) as o2i8,
			sum(ifn(op=2 and in=9,size1,.)*ret)/sum(ifn(op=2 and in=9,size1,.)) as o2i9,
			sum(ifn(op=3 and in=0,size1,.)*ret)/sum(ifn(op=3 and in=0,size1,.)) as o3i0,
			sum(ifn(op=3 and in=1,size1,.)*ret)/sum(ifn(op=3 and in=1,size1,.)) as o3i1,
			sum(ifn(op=3 and in=2,size1,.)*ret)/sum(ifn(op=3 and in=2,size1,.)) as o3i2,
			sum(ifn(op=3 and in=3,size1,.)*ret)/sum(ifn(op=3 and in=3,size1,.)) as o3i3,
			sum(ifn(op=3 and in=4,size1,.)*ret)/sum(ifn(op=3 and in=4,size1,.)) as o3i4,
			sum(ifn(op=3 and in=5,size1,.)*ret)/sum(ifn(op=3 and in=5,size1,.)) as o3i5,
			sum(ifn(op=3 and in=6,size1,.)*ret)/sum(ifn(op=3 and in=6,size1,.)) as o3i6,
			sum(ifn(op=3 and in=7,size1,.)*ret)/sum(ifn(op=3 and in=7,size1,.)) as o3i7,
			sum(ifn(op=3 and in=8,size1,.)*ret)/sum(ifn(op=3 and in=8,size1,.)) as o3i8,
			sum(ifn(op=3 and in=9,size1,.)*ret)/sum(ifn(op=3 and in=9,size1,.)) as o3i9,
			sum(ifn(op=4 and in=0,size1,.)*ret)/sum(ifn(op=4 and in=0,size1,.)) as o4i0,
			sum(ifn(op=4 and in=1,size1,.)*ret)/sum(ifn(op=4 and in=1,size1,.)) as o4i1,
			sum(ifn(op=4 and in=2,size1,.)*ret)/sum(ifn(op=4 and in=2,size1,.)) as o4i2,
			sum(ifn(op=4 and in=3,size1,.)*ret)/sum(ifn(op=4 and in=3,size1,.)) as o4i3,
			sum(ifn(op=4 and in=4,size1,.)*ret)/sum(ifn(op=4 and in=4,size1,.)) as o4i4,
			sum(ifn(op=4 and in=5,size1,.)*ret)/sum(ifn(op=4 and in=5,size1,.)) as o4i5,
			sum(ifn(op=4 and in=6,size1,.)*ret)/sum(ifn(op=4 and in=6,size1,.)) as o4i6,
			sum(ifn(op=4 and in=7,size1,.)*ret)/sum(ifn(op=4 and in=7,size1,.)) as o4i7,
			sum(ifn(op=4 and in=8,size1,.)*ret)/sum(ifn(op=4 and in=8,size1,.)) as o4i8,
			sum(ifn(op=4 and in=9,size1,.)*ret)/sum(ifn(op=4 and in=9,size1,.)) as o4i9,
			sum(ifn(op=5 and in=0,size1,.)*ret)/sum(ifn(op=5 and in=0,size1,.)) as o5i0,
			sum(ifn(op=5 and in=1,size1,.)*ret)/sum(ifn(op=5 and in=1,size1,.)) as o5i1,
			sum(ifn(op=5 and in=2,size1,.)*ret)/sum(ifn(op=5 and in=2,size1,.)) as o5i2,
			sum(ifn(op=5 and in=3,size1,.)*ret)/sum(ifn(op=5 and in=3,size1,.)) as o5i3,
			sum(ifn(op=5 and in=4,size1,.)*ret)/sum(ifn(op=5 and in=4,size1,.)) as o5i4,
			sum(ifn(op=5 and in=5,size1,.)*ret)/sum(ifn(op=5 and in=5,size1,.)) as o5i5,
			sum(ifn(op=5 and in=6,size1,.)*ret)/sum(ifn(op=5 and in=6,size1,.)) as o5i6,
			sum(ifn(op=5 and in=7,size1,.)*ret)/sum(ifn(op=5 and in=7,size1,.)) as o5i7,
			sum(ifn(op=5 and in=8,size1,.)*ret)/sum(ifn(op=5 and in=8,size1,.)) as o5i8,
			sum(ifn(op=5 and in=9,size1,.)*ret)/sum(ifn(op=5 and in=9,size1,.)) as o5i9,
			sum(ifn(op=6 and in=0,size1,.)*ret)/sum(ifn(op=6 and in=0,size1,.)) as o6i0,
			sum(ifn(op=6 and in=1,size1,.)*ret)/sum(ifn(op=6 and in=1,size1,.)) as o6i1,
			sum(ifn(op=6 and in=2,size1,.)*ret)/sum(ifn(op=6 and in=2,size1,.)) as o6i2,
			sum(ifn(op=6 and in=3,size1,.)*ret)/sum(ifn(op=6 and in=3,size1,.)) as o6i3,
			sum(ifn(op=6 and in=4,size1,.)*ret)/sum(ifn(op=6 and in=4,size1,.)) as o6i4,
			sum(ifn(op=6 and in=5,size1,.)*ret)/sum(ifn(op=6 and in=5,size1,.)) as o6i5,
			sum(ifn(op=6 and in=6,size1,.)*ret)/sum(ifn(op=6 and in=6,size1,.)) as o6i6,
			sum(ifn(op=6 and in=7,size1,.)*ret)/sum(ifn(op=6 and in=7,size1,.)) as o6i7,
			sum(ifn(op=6 and in=8,size1,.)*ret)/sum(ifn(op=6 and in=8,size1,.)) as o6i8,
			sum(ifn(op=6 and in=9,size1,.)*ret)/sum(ifn(op=6 and in=9,size1,.)) as o6i9,
			sum(ifn(op=7 and in=0,size1,.)*ret)/sum(ifn(op=7 and in=0,size1,.)) as o7i0,
			sum(ifn(op=7 and in=1,size1,.)*ret)/sum(ifn(op=7 and in=1,size1,.)) as o7i1,
			sum(ifn(op=7 and in=2,size1,.)*ret)/sum(ifn(op=7 and in=2,size1,.)) as o7i2,
			sum(ifn(op=7 and in=3,size1,.)*ret)/sum(ifn(op=7 and in=3,size1,.)) as o7i3,
			sum(ifn(op=7 and in=4,size1,.)*ret)/sum(ifn(op=7 and in=4,size1,.)) as o7i4,
			sum(ifn(op=7 and in=5,size1,.)*ret)/sum(ifn(op=7 and in=5,size1,.)) as o7i5,
			sum(ifn(op=7 and in=6,size1,.)*ret)/sum(ifn(op=7 and in=6,size1,.)) as o7i6,
			sum(ifn(op=7 and in=7,size1,.)*ret)/sum(ifn(op=7 and in=7,size1,.)) as o7i7,
			sum(ifn(op=7 and in=8,size1,.)*ret)/sum(ifn(op=7 and in=8,size1,.)) as o7i8,
			sum(ifn(op=7 and in=9,size1,.)*ret)/sum(ifn(op=7 and in=9,size1,.)) as o7i9,
			sum(ifn(op=8 and in=0,size1,.)*ret)/sum(ifn(op=8 and in=0,size1,.)) as o8i0,
			sum(ifn(op=8 and in=1,size1,.)*ret)/sum(ifn(op=8 and in=1,size1,.)) as o8i1,
			sum(ifn(op=8 and in=2,size1,.)*ret)/sum(ifn(op=8 and in=2,size1,.)) as o8i2,
			sum(ifn(op=8 and in=3,size1,.)*ret)/sum(ifn(op=8 and in=3,size1,.)) as o8i3,
			sum(ifn(op=8 and in=4,size1,.)*ret)/sum(ifn(op=8 and in=4,size1,.)) as o8i4,
			sum(ifn(op=8 and in=5,size1,.)*ret)/sum(ifn(op=8 and in=5,size1,.)) as o8i5,
			sum(ifn(op=8 and in=6,size1,.)*ret)/sum(ifn(op=8 and in=6,size1,.)) as o8i6,
			sum(ifn(op=8 and in=7,size1,.)*ret)/sum(ifn(op=8 and in=7,size1,.)) as o8i7,
			sum(ifn(op=8 and in=8,size1,.)*ret)/sum(ifn(op=8 and in=8,size1,.)) as o8i8,
			sum(ifn(op=8 and in=9,size1,.)*ret)/sum(ifn(op=8 and in=9,size1,.)) as o8i9,
			sum(ifn(op=9 and in=0,size1,.)*ret)/sum(ifn(op=9 and in=0,size1,.)) as o9i0,
			sum(ifn(op=9 and in=1,size1,.)*ret)/sum(ifn(op=9 and in=1,size1,.)) as o9i1,
			sum(ifn(op=9 and in=2,size1,.)*ret)/sum(ifn(op=9 and in=2,size1,.)) as o9i2,
			sum(ifn(op=9 and in=3,size1,.)*ret)/sum(ifn(op=9 and in=3,size1,.)) as o9i3,
			sum(ifn(op=9 and in=4,size1,.)*ret)/sum(ifn(op=9 and in=4,size1,.)) as o9i4,
			sum(ifn(op=9 and in=5,size1,.)*ret)/sum(ifn(op=9 and in=5,size1,.)) as o9i5,
			sum(ifn(op=9 and in=6,size1,.)*ret)/sum(ifn(op=9 and in=6,size1,.)) as o9i6,
			sum(ifn(op=9 and in=7,size1,.)*ret)/sum(ifn(op=9 and in=7,size1,.)) as o9i7,
			sum(ifn(op=9 and in=8,size1,.)*ret)/sum(ifn(op=9 and in=8,size1,.)) as o9i8,
			sum(ifn(op=9 and in=9,size1,.)*ret)/sum(ifn(op=9 and in=9,size1,.)) as o9i9
		from ret_op_in
		group by date
		order by date;
quit;

proc download out=r.ret_op_in_10x10;
run;

endrsubmit;
